# -*- coding: utf-8 -*-
"""Tarea 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wbXECyXv79eqa8lPyvknMkfOWn97-Ezh
"""

import math

# Datos del problema
g = 9.81      # m/s^2
m = 68.1      # kg
t = 10.0      # s
v_objetivo = 40.0  # m/s

def f(c):
    """
    Función cuya raíz queremos encontrar:
    f(c) = v_teórica(c) - v_objetivo
    """
    return g * m / c * (1.0 - math.exp(-c * t / m)) - v_objetivo

# Intervalo inicial para la bisección
a = 1e-6   # extremo izquierdo (c > 0)
b = 100.0  # extremo derecho

# Verificamos que haya cambio de signo
fa = f(a)
fb = f(b)

if fa * fb > 0:
    print("Error: el intervalo inicial no encierra una raíz.")
else:
    # Método de bisección
    for _ in range(100):
        c_med = 0.5 * (a + b)
        f_med = f(c_med)

        if fa * f_med <= 0:
            b = c_med
            fb = f_med
        else:
            a = c_med
            fa = f_med

    c_aprox = 0.5 * (a + b)
    print("Valor aproximado de c:", c_aprox, "kg/s")